# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Window.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(571, 482)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 210, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 232, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(109, 105, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 140, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 210, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 232, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 210, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 232, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(109, 105, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 140, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 210, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 232, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(109, 105, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 210, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 232, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(109, 105, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 140, 145))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(109, 105, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(109, 105, 108))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 210, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 210, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(218, 210, 217))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        Window.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(Window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_10 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_10.setOrientation(QtCore.Qt.Vertical)
        self.splitter_10.setObjectName("splitter_10")
        self.splitter_7 = QtWidgets.QSplitter(self.splitter_10)
        self.splitter_7.setMinimumSize(QtCore.QSize(0, 350))
        self.splitter_7.setMaximumSize(QtCore.QSize(16777215, 350))
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName("splitter_7")
        self.splitter_6 = QtWidgets.QSplitter(self.splitter_7)
        self.splitter_6.setMinimumSize(QtCore.QSize(187, 350))
        self.splitter_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter_6.setOrientation(QtCore.Qt.Vertical)
        self.splitter_6.setObjectName("splitter_6")
        self.contacts = QtWidgets.QLabel(self.splitter_6)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(14)
        self.contacts.setFont(font)
        self.contacts.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.contacts.setTextFormat(QtCore.Qt.AutoText)
        self.contacts.setScaledContents(False)
        self.contacts.setAlignment(QtCore.Qt.AlignCenter)
        self.contacts.setWordWrap(False)
        self.contacts.setObjectName("contacts")
        self.listWidget = QtWidgets.QListWidget(self.splitter_6)
        self.listWidget.setMinimumSize(QtCore.QSize(0, 320))
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 320))
        self.listWidget.setObjectName("listWidget")
        self.splitter_5 = QtWidgets.QSplitter(self.splitter_7)
        self.splitter_5.setMinimumSize(QtCore.QSize(0, 350))
        self.splitter_5.setOrientation(QtCore.Qt.Vertical)
        self.splitter_5.setObjectName("splitter_5")
        self.chat = QtWidgets.QLabel(self.splitter_5)
        self.chat.setMinimumSize(QtCore.QSize(360, 25))
        self.chat.setMaximumSize(QtCore.QSize(360, 25))
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(14)
        self.chat.setFont(font)
        self.chat.setAlignment(QtCore.Qt.AlignCenter)
        self.chat.setObjectName("chat")
        self.storyMessage = QtWidgets.QListWidget(self.splitter_5)
        self.storyMessage.setMinimumSize(QtCore.QSize(360, 320))
        self.storyMessage.setMaximumSize(QtCore.QSize(360, 320))
        self.storyMessage.setObjectName("storyMessage")
        self.splitter_9 = QtWidgets.QSplitter(self.splitter_10)
        self.splitter_9.setMaximumSize(QtCore.QSize(552, 16777215))
        self.splitter_9.setOrientation(QtCore.Qt.Vertical)
        self.splitter_9.setObjectName("splitter_9")
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_9)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.textEdit = QtWidgets.QTextEdit(self.splitter_4)
        self.textEdit.setMinimumSize(QtCore.QSize(0, 32))
        self.textEdit.setMaximumSize(QtCore.QSize(187, 32))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.textEdit.setFont(font)
        self.textEdit.setDocumentTitle("")
        self.textEdit.setObjectName("textEdit")
        self.splitter_2 = QtWidgets.QSplitter(self.splitter_4)
        self.splitter_2.setMaximumSize(QtCore.QSize(288, 32))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setHandleWidth(0)
        self.splitter_2.setObjectName("splitter_2")
        self.Bt_bold = QtWidgets.QPushButton(self.splitter_2)
        self.Bt_bold.setMinimumSize(QtCore.QSize(32, 32))
        self.Bt_bold.setMaximumSize(QtCore.QSize(32, 32))
        self.Bt_bold.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Bt_bold.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/b.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Bt_bold.setIcon(icon)
        self.Bt_bold.setIconSize(QtCore.QSize(32, 32))
        self.Bt_bold.setObjectName("Bt_bold")
        self.Bt_italic = QtWidgets.QPushButton(self.splitter_2)
        self.Bt_italic.setMinimumSize(QtCore.QSize(32, 32))
        self.Bt_italic.setMaximumSize(QtCore.QSize(32, 32))
        self.Bt_italic.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/i.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Bt_italic.setIcon(icon1)
        self.Bt_italic.setIconSize(QtCore.QSize(32, 32))
        self.Bt_italic.setObjectName("Bt_italic")
        self.Bt_underlined = QtWidgets.QPushButton(self.splitter_2)
        self.Bt_underlined.setMinimumSize(QtCore.QSize(32, 32))
        self.Bt_underlined.setMaximumSize(QtCore.QSize(32, 32))
        self.Bt_underlined.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/u.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Bt_underlined.setIcon(icon2)
        self.Bt_underlined.setIconSize(QtCore.QSize(32, 32))
        self.Bt_underlined.setObjectName("Bt_underlined")
        self.Bt_smile = QtWidgets.QPushButton(self.splitter_2)
        self.Bt_smile.setMinimumSize(QtCore.QSize(32, 32))
        self.Bt_smile.setMaximumSize(QtCore.QSize(32, 32))
        self.Bt_smile.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/smile.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Bt_smile.setIcon(icon3)
        self.Bt_smile.setIconSize(QtCore.QSize(25, 25))
        self.Bt_smile.setObjectName("Bt_smile")
        self.tongue = QtWidgets.QPushButton(self.splitter_2)
        self.tongue.setMinimumSize(QtCore.QSize(32, 32))
        self.tongue.setMaximumSize(QtCore.QSize(32, 32))
        self.tongue.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/tongue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tongue.setIcon(icon4)
        self.tongue.setIconSize(QtCore.QSize(25, 25))
        self.tongue.setObjectName("tongue")
        self.wink = QtWidgets.QPushButton(self.splitter_2)
        self.wink.setMinimumSize(QtCore.QSize(32, 32))
        self.wink.setMaximumSize(QtCore.QSize(32, 32))
        self.wink.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("icons/wink.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.wink.setIcon(icon5)
        self.wink.setIconSize(QtCore.QSize(25, 25))
        self.wink.setObjectName("wink")
        self.suspect = QtWidgets.QPushButton(self.splitter_2)
        self.suspect.setMinimumSize(QtCore.QSize(32, 32))
        self.suspect.setMaximumSize(QtCore.QSize(32, 32))
        self.suspect.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("icons/suspect.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.suspect.setIcon(icon6)
        self.suspect.setIconSize(QtCore.QSize(25, 25))
        self.suspect.setObjectName("suspect")
        self.indifferent = QtWidgets.QPushButton(self.splitter_2)
        self.indifferent.setMinimumSize(QtCore.QSize(32, 32))
        self.indifferent.setMaximumSize(QtCore.QSize(32, 32))
        self.indifferent.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("icons/indifferent.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.indifferent.setIcon(icon7)
        self.indifferent.setIconSize(QtCore.QSize(25, 25))
        self.indifferent.setObjectName("indifferent")
        self.kiss = QtWidgets.QPushButton(self.splitter_2)
        self.kiss.setMinimumSize(QtCore.QSize(32, 32))
        self.kiss.setMaximumSize(QtCore.QSize(32, 32))
        self.kiss.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("icons/kiss.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.kiss.setIcon(icon8)
        self.kiss.setIconSize(QtCore.QSize(25, 25))
        self.kiss.setObjectName("kiss")
        self.splitter_8 = QtWidgets.QSplitter(self.splitter_9)
        self.splitter_8.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_8.setObjectName("splitter_8")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_8)
        self.splitter_3.setMinimumSize(QtCore.QSize(187, 0))
        self.splitter_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.ButtonAdd = QtWidgets.QPushButton(self.splitter_3)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(11)
        self.ButtonAdd.setFont(font)
        self.ButtonAdd.setIconSize(QtCore.QSize(32, 32))
        self.ButtonAdd.setObjectName("ButtonAdd")
        self.ButtonDelete = QtWidgets.QPushButton(self.splitter_3)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(11)
        self.ButtonDelete.setFont(font)
        self.ButtonDelete.setIconSize(QtCore.QSize(30, 30))
        self.ButtonDelete.setAutoDefault(False)
        self.ButtonDelete.setObjectName("ButtonDelete")
        self.splitter = QtWidgets.QSplitter(self.splitter_8)
        self.splitter.setMinimumSize(QtCore.QSize(360, 0))
        self.splitter.setMaximumSize(QtCore.QSize(360, 16777215))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(2)
        self.splitter.setObjectName("splitter")
        self.InputText = QtWidgets.QTextEdit(self.splitter)
        self.InputText.setMaximumSize(QtCore.QSize(302, 16777215))
        self.InputText.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.InputText.setObjectName("InputText")
        self.ButtonSend = QtWidgets.QPushButton(self.splitter)
        self.ButtonSend.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Copperplate Gothic Bold")
        font.setPointSize(13)
        self.ButtonSend.setFont(font)
        self.ButtonSend.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ButtonSend.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.ButtonSend.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ButtonSend.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("icons/036-paper-plane.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ButtonSend.setIcon(icon9)
        self.ButtonSend.setIconSize(QtCore.QSize(60, 60))
        self.ButtonSend.setCheckable(False)
        self.ButtonSend.setAutoRepeat(False)
        self.ButtonSend.setObjectName("ButtonSend")
        self.gridLayout.addWidget(self.splitter_10, 0, 0, 1, 1)
        Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(Window)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "Converse"))
        self.contacts.setText(_translate("Window", "contacts"))
        self.chat.setText(_translate("Window", "chat"))
        self.textEdit.setPlaceholderText(_translate("Window", "contact"))
        self.ButtonAdd.setText(_translate("Window", "add"))
        self.ButtonDelete.setText(_translate("Window", "del"))
